name: 'Attach document to Confluence'
description: 'Attach a document to a named Confluence page'
inputs:
  domain:
    description: 'Your Atlassian domain'
    required: true
  spacekey:
    description: 'Space key where page is located'
    required: true
  pageheading:
    description: 'Title of the Confluence page to attach the document to'
    required: true
  destinationname:
    description: 'The filename to attach the document with'
    required: true
  sourcename:
    description: 'The filename of the local file to attach'
    required: true
  email:
    description: 'Email address of user owning the API token used to access confluence API'
    required: true
  token:
    description: 'Confluence API token to use accessing Confluence API'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/streeva/attach-document-confluence:v2.0.0'
  args:
    - ${{ inputs.domain }}
    - ${{ inputs.spacekey }}
    - ${{ inputs.pageheading }}
    - ${{ inputs.destinationname }}
    - ${{ inputs.sourcename }}
    - ${{ inputs.email }}
    - ${{ inputs.token }}